# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='estado',
            field=models.CharField(choices=[('DIS', 'disponible'), ('AG', 'agotado')], default='DIS', max_length=50),
        ),
    ]
